language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test-only

after_success:
  - npm run gendoc
  - npm run preparedistLinux

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: documentation/
    github_token: $GITHUB_TOKEN

  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "./dist/fractal-typescript.tar.gz"
    skip_cleanup: true
    on:
      branch: master
      tags: true
