language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test-only

after_success:
  - npm run gendoc

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: documentation/
    github_token: $GITHUB_TOKEN