defaults: &defaults
  working_directory: ~/fractal-typescript
  docker:
    - image: circleci/node:8.0

whitelist: &whitelist
  paths:
    - .npmignore
    - coverage/*
    - dist/*
    - node_modules/*
    - src/*
    - test/*
    - CODE_OF_CONDUCT.md
    - LICENSE.md
    - package.json
    - README.md
    - tsconfig.json
    - tslint.json

version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            -
      - run:
          name: Install Dependencies
          command: npm run install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

#  lint:
#    <<: *defaults
#
#    steps:
#      - attach_workspace:
#          at: ~/repo
#
#      - run:
#          name: Lint TypeScript code
#          command: npm run lint

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Test TypeScript code
          command: npm run test-only

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build TypeScript code
          command: npm run build

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  buildDoc:
    <<: *defaults

    steps:
      - attach_workespace:
          at: ~/repo

      - run:
          name: Build Doc
          command: npm run gendoc

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

workflows:
  version: 2

  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
#      - lint:
#          requires:
#            - checkout
      - coveralls:
          requires:
            - test
      - build:
          requires:
            - test
#            - lint
      - builDoc:
          requires:
            - build
