defaults: &defaults
  working_directory: ~/fractal-typescript
  docker:
    - image: circleci/node:latest

whitelist: &whitelist
  paths:
    - .npmignore
    - .git/*
    - .gitignore
    - coverage/*
    - dist/*
    - node_modules/*
    - src/*
    - test/*
    - CODE_OF_CONDUCT.md
    - LICENSE.md
    - package.json
    - README.md
    - tsconfig.json
    - tslint.json
    - jest.config.js
    - documentation/*

version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm run installScript

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/fractal-typescript
          <<: *whitelist

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/fractal-typescript

      - run:
          name: Lint TypeScript code
          command: npm run tslint

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/fractal-typescript

      - run:
          name: Test TypeScript code
          command: npm run test

      - persist_to_workspace:
          root: ~/fractal-typescript
          <<: *whitelist

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/fractal-typescript

      - run:
          name: Build TypeScript code
          command: npm run build

      - persist_to_workspace:
          root: ~/fractal-typescript
          <<: *whitelist

  buildDoc:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/fractal-typescript

      - run:
          name: Build Doc
          command: npm run gendoc

      - persist_to_workspace:
          root: ~/fractal-typescript
          <<: *whitelist

  releaseDoc:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/fractal-typescript

      - run:
          name: Install and configure dependencies
          command: |
            mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
            echo "github.com,192.30.253.112 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
            sudo npm i -g --silent gh-pages
            git config user.email "build-bot@outlook.de"
            git config user.name "fractal-typescript-ci-bot"

      - add_ssh_keys:
          fingerprints:
            - "83:37:63:ee:05:f0:c1:92:fe:4b:3c:63:b2:0d:26:7d"

      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist documentation

workflows:
  version: 2

  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - build:
          requires:
            - test
            - lint
      - buildDoc:
          requires:
            - build
          filters:
            branches:
              only: master
      - releaseDoc:
          requires:
            - buildDoc
          filters:
            branches:
              only: master
